### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 9898287**

### CODE REVIEW

**Comment by timotheecour** [comment]
thanks!

> [D] FFI Works in CTFE

how so?
IIRC can't use functions without source code in CTFE in D (such as printf etc)

**Comment by 9898287** [comment]
stdc is built into the D standard library, printf works fine.

**Comment by timotheecour** [comment]
D:
dmd -o- main.d
```d
void main(){
  import core.stdc.stdio;
  enum s=printf("hello\n");
}
```
Error: printf cannot be interpreted at compile time, because it has no available source code

/cc @9898287 happy to merge once you address that point

**Comment by 9898287** [comment]
Ah, I see what you mean.

**Comment by timotheecour** [comment]
merged but fixed that comment i mentioned in https://github.com/timotheecour/D_vs_nim/commit/3ee5760c1f3011287fd7ac75b5489e014fc2bbd6 ; thanks!

**Pull request merged**
